const express  = require('express');
const axios    = require('axios');
const { ForecastResult, Product, User, Alert, PurchaseOrder } = require('../models');
const { authenticate, requireRole } = require('../middleware/auth.middleware');

const router = express.Router();
router.use(authenticate);

// GET /api/forecast
router.get('/', async (req, res) => {
    try {
        const { risk_level, product_id } = req.query;
        const query = {};
        if (risk_level)  query.risk_level  = risk_level;
        if (product_id)  query.product_id  = product_id;

        const rows = await ForecastResult.find(query)
            .populate('product_id', 'name sku category current_stock reorder_level unit_price vendor_id')
            .sort({ _id: -1 })
            .limit(200);

        const result = rows.map(r => ({
            id:            r._id,
            product_id:    r.product_id?._id,
            forecast_date: r.forecast_date,
            predicted_qty: r.predicted_qty,
            confidence:    r.confidence,
            risk_level:    r.risk_level,
            Product: {
                id:            r.product_id?._id,
                name:          r.product_id?.name || ('Product #' + r.product_id),
                sku:           r.product_id?.sku || '',
                category:      r.product_id?.category || '',
                current_stock: r.product_id?.current_stock || 0,
                reorder_level: r.product_id?.reorder_level || 0,
                unit_price:    r.product_id?.unit_price || 0,
                vendor_id:     r.product_id?.vendor_id || null
            }
        }));

        res.json(result);
    } catch (err) {
        console.error('[GET /forecast] error:', err.message);
        res.status(500).json({ error: err.message });
    }
});

// POST /api/forecast/run
router.post('/run', requireRole('ADMIN', 'MANAGER'), async (req, res) => {
    try {
        const mlUrl      = process.env.ML_SERVICE_URL || 'http://localhost:8000';
        const mlResponse = await axios.post(`${mlUrl}/forecast`, {}, { timeout: 60000 });
        const mlData     = mlResponse.data;
        const savedForecasts = mlData.forecasts || [];

        if (Array.isArray(savedForecasts)) {
            for (const item of savedForecasts) {
                try {
                    if (['HIGH', 'CRITICAL'].includes(item.risk_level)) {
                        const product = await Product.findById(item.product_id)
                            .populate('vendor_id', 'id name email');

                        if (product) {
                            await Alert.deleteMany({ product_id: product._id, type: 'RESTOCK_SUGGESTED' });
                            await Alert.create({
                                product_id: product._id,
                                vendor_id:  product.vendor_id?._id || null,
                                type:       'RESTOCK_SUGGESTED',
                                message:    `AI Forecast: ${product.name} (${product.sku}) — Risk: ${item.risk_level}. Predicted demand: ${Math.ceil(item.predicted_qty)} units in next 7 days. Current stock: ${product.current_stock}.`,
                                is_read:    false
                            });

                            if (product.vendor_id) {
                                const existingPO = await PurchaseOrder.findOne({
                                    product_id: product._id,
                                    status: { $in: ['PENDING', 'APPROVED'] }
                                });

                                if (!existingPO) {
                                    const reorderQty = Math.max(
                                        (product.reorder_level || 10) * 2,
                                        Math.ceil(item.predicted_qty)
                                    );
                                    const newPO = await PurchaseOrder.create({
                                        product_id: product._id,
                                        vendor_id:  product.vendor_id._id,
                                        quantity:   reorderQty,
                                        status:     'PENDING',
                                        notes:      `Auto-generated by AI forecast. Risk: ${item.risk_level}. Predicted demand: ${Math.ceil(item.predicted_qty)} units.`
                                    });

                                    try {
                                        const { sendPurchaseOrderEmail } = require('../utils/mailer');
                                        await sendPurchaseOrderEmail({
                                            vendorEmail: product.vendor_id.email,
                                            vendorName:  product.vendor_id.name,
                                            productName: product.name,
                                            productSku:  product.sku,
                                            quantity:    reorderQty,
                                            orderId:     newPO._id,
                                            notes:       `Auto-generated by AI forecast. Risk: ${item.risk_level}.`
                                        });
                                    } catch (mailErr) {
                                        console.error(`Email failed for PO ${newPO._id}:`, mailErr.message);
                                    }
                                }
                            }
                        }
                    }
                } catch (itemErr) {
                    console.error(`Alert/PO error for product ${item.product_id}:`, itemErr.message);
                }
            }
        }

        res.json({
            success:    true,
            message:    `Forecast completed. ${savedForecasts.length} products updated.`,
            forecasts:  savedForecasts,
            accuracy:   mlData.model_accuracy || null,
            ran_at:     mlData.trained_at || new Date().toISOString()
        });
    } catch (err) {
        if (err.code === 'ECONNREFUSED' || err.code === 'ETIMEDOUT') {
            return res.status(503).json({ error: 'ML service is not running. Start ml-service/main.py first.' });
        }
        res.status(500).json({ error: err.message });
    }
});

// GET /api/forecast/:product_id
router.get('/:product_id', async (req, res) => {
    try {
        const product = await Product.findById(req.params.product_id);
        if (!product) return res.status(404).json({ error: 'Product not found' });

        const forecasts = await ForecastResult.find({ product_id: req.params.product_id })
            .populate('product_id', 'id name sku current_stock reorder_level')
            .sort({ forecast_date: 1 })
            .limit(30);

        res.json(forecasts);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// POST /api/forecast/trigger-alerts
router.post('/trigger-alerts', requireRole('ADMIN', 'MANAGER'), async (req, res) => {
    try {
        const forecasts = await ForecastResult.find({ risk_level: { $in: ['HIGH', 'CRITICAL'] } })
            .populate({ path: 'product_id', populate: { path: 'vendor_id', select: 'id name email' } });

        let created = 0;
        for (const f of forecasts) {
            const product = f.product_id;
            if (!product) continue;

            await Alert.deleteMany({ product_id: product._id, type: 'RESTOCK_SUGGESTED' });
            await Alert.create({
                product_id: product._id,
                vendor_id:  product.vendor_id?._id || null,
                type:       'RESTOCK_SUGGESTED',
                message:    `AI Forecast: ${product.name} (${product.sku}) — Risk: ${f.risk_level}. Predicted demand: ${Math.ceil(f.predicted_qty)} units in next 7 days. Current stock: ${product.current_stock}.`,
                is_read:    false
            });
            created++;
        }

        res.json({ success: true, alerts_created: created });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

module.exports = router;